// <auto-generated />
using System;
using GrifballWebApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrifballWebApp.Migrations.Postgres.Migrations
{
    [DbContext(typeof(GrifballContext))]
    [Migration("20261010221758_RowHistory")]
    partial class RowHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrifballWebApp.Database.Models.AvailabilityOption", b =>
                {
                    b.Property<int>("AvailabilityOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvailabilityOptionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.HasKey("AvailabilityOptionID");

                    b.HasIndex("DayOfWeek", "Time")
                        .IsUnique();

                    b.ToTable("AvailabilityOptions", "Event");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.DiscordMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<long>("FromDiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ToDiscordUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromDiscordUserId");

                    b.HasIndex("ToDiscordUserId");

                    b.ToTable("Messages", "Discord");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.DiscordUser", b =>
                {
                    b.Property<long>("DiscordUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<string>("DiscordUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("DiscordUserID");

                    b.ToTable("Discord", "User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.GameVersion", b =>
                {
                    b.Property<int>("GameVesionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameVesionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<string>("GameVersionName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("GameVesionID");

                    b.HasIndex("GameVersionName")
                        .IsUnique();

                    b.ToTable("GameVersions", "Other");

                    b.HasData(
                        new
                        {
                            GameVesionID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameVersionName = "Halo 3",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameVesionID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameVersionName = "Halo Reach",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameVesionID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameVersionName = "Halo Reach Dash",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameVesionID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameVersionName = "Halo 4",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameVesionID = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameVersionName = "Halo 5",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GameVesionID = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameVersionName = "Halo Infinite",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Match", b =>
                {
                    b.Property<Guid>("MatchID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StatsPullDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MatchID");

                    b.ToTable("Matches", "Infinite");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchBracketInfo", b =>
                {
                    b.Property<int>("MatchBracketInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchBracketInfoID"));

                    b.Property<int?>("AwayTeamPreviousMatchBracketInfoID")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamSeedNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Bracket")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamPreviousMatchBracketInfoID")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamSeedNumber")
                        .HasColumnType("integer");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonMatchID")
                        .HasColumnType("integer");

                    b.HasKey("MatchBracketInfoID");

                    b.HasIndex("AwayTeamPreviousMatchBracketInfoID");

                    b.HasIndex("HomeTeamPreviousMatchBracketInfoID");

                    b.HasIndex("SeasonMatchID")
                        .IsUnique();

                    b.ToTable("MatchBracketInfo", "Event", t =>
                        {
                            t.HasCheckConstraint("CK_Event_MatchBracketInfo_RequireAwaySeedOrPreviousMatch", "(\"AwayTeamSeedNumber\" IS NOT NULL AND \"AwayTeamPreviousMatchBracketInfoID\" IS NULL) OR (\"AwayTeamPreviousMatchBracketInfoID\" IS NOT NULL AND \"AwayTeamSeedNumber\" IS NULL)");

                            t.HasCheckConstraint("CK_Event_MatchBracketInfo_RequireHomeSeedOrPreviousMatch", "(\"HomeTeamSeedNumber\" IS NOT NULL AND \"HomeTeamPreviousMatchBracketInfoID\" IS NULL) OR (\"HomeTeamPreviousMatchBracketInfoID\" IS NOT NULL AND \"HomeTeamSeedNumber\" IS NULL)");
                        });
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchLink", b =>
                {
                    b.Property<int>("MatchLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchLinkID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchID")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonMatchID")
                        .HasColumnType("integer");

                    b.HasKey("MatchLinkID");

                    b.HasIndex("MatchID")
                        .IsUnique();

                    b.HasIndex("SeasonMatchID", "MatchNumber")
                        .IsUnique();

                    b.ToTable("MatchLinks", "Event");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchParticipant", b =>
                {
                    b.Property<Guid>("MatchID")
                        .HasColumnType("uuid");

                    b.Property<long>("XboxUserID")
                        .HasColumnType("bigint");

                    b.Property<float>("Accuracy")
                        .HasColumnType("real");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("AverageLife")
                        .HasColumnType("interval");

                    b.Property<int>("Betrayals")
                        .HasColumnType("integer");

                    b.Property<int>("CalloutAssists")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("integer");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstJoinedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("JoinedInProgress")
                        .HasColumnType("boolean");

                    b.Property<float>("Kda")
                        .HasColumnType("real");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLeaveTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LeftInProgress")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxKillingSpree")
                        .HasColumnType("integer");

                    b.Property<int>("MeleeKills")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("ObjectivesCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("PersonalScore")
                        .HasColumnType("integer");

                    b.Property<int>("PowerWeaponKills")
                        .HasColumnType("integer");

                    b.Property<bool>("PresentAtBeginning")
                        .HasColumnType("boolean");

                    b.Property<bool>("PresentAtCompletion")
                        .HasColumnType("boolean");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("RoundsLost")
                        .HasColumnType("integer");

                    b.Property<int>("RoundsTied")
                        .HasColumnType("integer");

                    b.Property<int>("RoundsWon")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsFired")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsHit")
                        .HasColumnType("integer");

                    b.Property<int>("Spawns")
                        .HasColumnType("integer");

                    b.Property<int>("Suicides")
                        .HasColumnType("integer");

                    b.Property<int>("TeamID")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TimePlayed")
                        .HasColumnType("interval");

                    b.HasKey("MatchID", "XboxUserID");

                    b.HasIndex("XboxUserID");

                    b.HasIndex("MatchID", "TeamID");

                    b.ToTable("MatchParticipants", "Infinite");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchReschedule", b =>
                {
                    b.Property<int>("MatchRescheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchRescheduleID"));

                    b.Property<int?>("ApprovedByUserID")
                        .HasColumnType("integer");

                    b.Property<string>("CommissionerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DiscordThreadID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NewScheduledTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("OriginalScheduledTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RequestedByUserID")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonMatchID")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("MatchRescheduleID");

                    b.HasIndex("ApprovedByUserID");

                    b.HasIndex("DiscordThreadID");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedByUserID");

                    b.HasIndex("SeasonMatchID");

                    b.HasIndex("Status");

                    b.ToTable("MatchReschedules");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchTeam", b =>
                {
                    b.Property<Guid>("MatchID")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("MatchID", "TeamID");

                    b.ToTable("MatchTeams", "Infinite");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedKickVote", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("VoterMatchedPlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<int>("KickMatchedPlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "VoterMatchedPlayerId");

                    b.HasIndex("KickMatchedPlayerId");

                    b.HasIndex("VoterMatchedPlayerId");

                    b.ToTable("MatchedKickVotes", "Matchmaking");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MatchID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("ThreadID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("VoteMessageID")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId")
                        .IsUnique();

                    b.HasIndex("HomeTeamId")
                        .IsUnique();

                    b.HasIndex("MatchID")
                        .IsUnique();

                    b.ToTable("MatchedMatches", "Matchmaking");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<bool>("Kicked")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchedTeamID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchedTeamID");

                    b.HasIndex("UserID");

                    b.ToTable("MatchedPlayers", "Matchmaking");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedTeam", b =>
                {
                    b.Property<int>("MatchedTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchedTeamId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("MatchedTeamId");

                    b.ToTable("MatchedTeams", "Matchmaking");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedWinnerVote", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("MatchedPlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("WinnerVote")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "MatchedPlayerId");

                    b.HasIndex("MatchedPlayerId");

                    b.ToTable("MatchedWinnerVotes", "Matchmaking");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Medal", b =>
                {
                    b.Property<long>("MedalID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<int>("MedalDifficultyID")
                        .HasColumnType("integer");

                    b.Property<string>("MedalName")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<int>("MedalTypeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("PersonalScore")
                        .HasColumnType("integer");

                    b.Property<int>("SortingWeight")
                        .HasColumnType("integer");

                    b.Property<int>("SpriteIndex")
                        .HasColumnType("integer");

                    b.HasKey("MedalID");

                    b.HasIndex("MedalDifficultyID");

                    b.HasIndex("MedalTypeID");

                    b.ToTable("Medals", "Infinite");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MedalDifficulty", b =>
                {
                    b.Property<int>("MedalDifficultyID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<string>("MedalDifficultyName")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("MedalDifficultyID");

                    b.ToTable("MedalDifficulties", "Infinite");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MedalEarned", b =>
                {
                    b.Property<long>("MedalID")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MatchID")
                        .HasColumnType("uuid");

                    b.Property<long>("XboxUserID")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPersonalScoreAwarded")
                        .HasColumnType("integer");

                    b.HasKey("MedalID", "MatchID", "XboxUserID");

                    b.HasIndex("MatchID", "XboxUserID");

                    b.ToTable("MedalEarned", "Infinite");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MedalType", b =>
                {
                    b.Property<int>("MedalTypeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<string>("MedalTypeName")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("MedalTypeID");

                    b.ToTable("MedalTypes", "Infinite");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.PasswordResetLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("und-x-icu");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetLinks", "Auth");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.QueuedPlayer", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("UserID");

                    b.ToTable("QueuedPlayers", "Matchmaking");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<byte[]>("Icon")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("MmrThreshold")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.HasKey("Id");

                    b.ToTable("Ranks", "Matchmaking");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("und-x-icu");

                    b.HasKey("RegionID");

                    b.HasIndex("RegionName")
                        .IsUnique();

                    b.ToTable("Regions", "Other");

                    b.HasData(
                        new
                        {
                            RegionID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegionName = "West North America"
                        },
                        new
                        {
                            RegionID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegionName = "Central North America"
                        },
                        new
                        {
                            RegionID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegionName = "East North America"
                        },
                        new
                        {
                            RegionID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegionName = "North Europe"
                        },
                        new
                        {
                            RegionID = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegionName = "South Europe"
                        },
                        new
                        {
                            RegionID = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegionName = "Australia"
                        });
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("und-x-icu");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("und-x-icu");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "cda78946-53d4-4154-b723-2b33b95341cc",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sysadmin",
                            NormalizedName = "SYSADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "37ff5fdf-5cb8-403c-bb9e-81db05a5fcdd",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Commissioner",
                            NormalizedName = "COMMISSIONER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "0be992c7-f824-40c7-8975-964068c7fbfe",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        });
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Season", b =>
                {
                    b.Property<int>("SeasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonID"));

                    b.Property<bool>("CaptainsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DraftStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SeasonEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("SeasonStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SignupsClose")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SignupsOpen")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("SeasonID");

                    b.HasIndex("SeasonName")
                        .IsUnique();

                    b.ToTable("Seasons", "Event");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SeasonAvailability", b =>
                {
                    b.Property<int>("SeasonID")
                        .HasColumnType("integer");

                    b.Property<int>("AvailabilityOptionID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("SeasonID", "AvailabilityOptionID");

                    b.HasIndex("AvailabilityOptionID");

                    b.ToTable("SeasonAvailability", "Event");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SeasonMatch", b =>
                {
                    b.Property<int>("SeasonMatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonMatchID"));

                    b.Property<int?>("ActiveRescheduleRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamID")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamResult")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamScore")
                        .HasColumnType("integer");

                    b.Property<int>("BestOf")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamID")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamResult")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SeasonID")
                        .HasColumnType("integer");

                    b.HasKey("SeasonMatchID");

                    b.HasIndex("ActiveRescheduleRequestId")
                        .IsUnique();

                    b.HasIndex("AwayTeamID");

                    b.HasIndex("HomeTeamID");

                    b.HasIndex("SeasonID");

                    b.ToTable("SeasonMatches", "Event", t =>
                        {
                            t.HasCheckConstraint("CK_Event_SeasonMatches_MustBeDifferentTeams", "(\"HomeTeamID\" IS NULL) OR (\"AwayTeamID\" IS NULL) OR (\"HomeTeamID\" != \"AwayTeamID\")");
                        });
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SeasonSignup", b =>
                {
                    b.Property<int>("SeasonSignupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonSignupID"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresAssistanceDrafting")
                        .HasColumnType("boolean");

                    b.Property<int>("SeasonID")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<bool>("WillCaptain")
                        .HasColumnType("boolean");

                    b.HasKey("SeasonSignupID");

                    b.HasIndex("SeasonID");

                    b.HasIndex("UserID", "SeasonID")
                        .IsUnique();

                    b.ToTable("SeasonSignups", "Event");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SignupAvailability", b =>
                {
                    b.Property<int>("SeasonSignupID")
                        .HasColumnType("integer");

                    b.Property<int>("AvailabilityOptionID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("SeasonSignupID", "AvailabilityOptionID");

                    b.HasIndex("AvailabilityOptionID");

                    b.ToTable("SignupAvailability", "Event");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamID"));

                    b.Property<int?>("CaptainID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonID")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .UseCollation("und-x-icu");

                    b.HasKey("TeamID");

                    b.HasIndex("CaptainID")
                        .IsUnique();

                    b.HasIndex("SeasonID");

                    b.HasIndex("TeamName", "SeasonID")
                        .IsUnique();

                    b.ToTable("Teams", "Event");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.TeamAvailability", b =>
                {
                    b.Property<int>("TeamID")
                        .HasColumnType("integer");

                    b.Property<int>("AvailabilityOptionID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("TeamID", "AvailabilityOptionID");

                    b.HasIndex("AvailabilityOptionID");

                    b.ToTable("TeamAvailability", "Event");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.TeamPlayer", b =>
                {
                    b.Property<int>("TeamPlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamPlayerID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftCaptainOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftPick")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("TeamID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("TeamPlayerID");

                    b.HasIndex("TeamID");

                    b.HasIndex("UserID", "TeamID")
                        .IsUnique();

                    b.ToTable("TeamPlayers", "Event");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<long?>("DiscordUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .UseCollation("und-x-icu");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("und-x-icu");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDummyUser")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LossStreak")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("MMR")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("und-x-icu");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("und-x-icu");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("RegionID")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("und-x-icu");

                    b.Property<int>("WinStreak")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.Property<long?>("XboxUserID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserID")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RegionID");

                    b.HasIndex("XboxUserID")
                        .IsUnique();

                    b.ToTable("Users", "Auth");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Auth");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.UserExperience", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("GameVersionID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("UserID", "GameVersionID");

                    b.HasIndex("GameVersionID");

                    b.ToTable("UserExperiences", "Other");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Auth");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Auth");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.XboxUser", b =>
                {
                    b.Property<long>("XboxUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<string>("Gamertag")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifiedByID")
                        .HasColumnType("integer");

                    b.HasKey("XboxUserID");

                    b.ToTable("XboxUsers", "Xbox");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Auth");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.DiscordMessage", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.DiscordUser", "FromDiscordUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("FromDiscordUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.DiscordUser", "ToDiscordUser")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ToDiscordUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromDiscordUser");

                    b.Navigation("ToDiscordUser");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchBracketInfo", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.MatchBracketInfo", "AwayTeamPreviousMatchBracketInfo")
                        .WithMany("InverseAwayTeamNextMatchBracketInfo")
                        .HasForeignKey("AwayTeamPreviousMatchBracketInfoID");

                    b.HasOne("GrifballWebApp.Database.Models.MatchBracketInfo", "HomeTeamPreviousMatchBracketInfo")
                        .WithMany("InverseHomeTeamPreviousMatchBracketInfo")
                        .HasForeignKey("HomeTeamPreviousMatchBracketInfoID");

                    b.HasOne("GrifballWebApp.Database.Models.SeasonMatch", "SeasonMatch")
                        .WithOne("BracketMatch")
                        .HasForeignKey("GrifballWebApp.Database.Models.MatchBracketInfo", "SeasonMatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeamPreviousMatchBracketInfo");

                    b.Navigation("HomeTeamPreviousMatchBracketInfo");

                    b.Navigation("SeasonMatch");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchLink", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.Match", "Match")
                        .WithOne("MatchLink")
                        .HasForeignKey("GrifballWebApp.Database.Models.MatchLink", "MatchID");

                    b.HasOne("GrifballWebApp.Database.Models.SeasonMatch", "SeasonMatch")
                        .WithMany("MatchLinks")
                        .HasForeignKey("SeasonMatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("SeasonMatch");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchParticipant", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.XboxUser", "XboxUser")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("XboxUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.MatchTeam", "MatchTeam")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("MatchID", "TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchTeam");

                    b.Navigation("XboxUser");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchReschedule", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GrifballWebApp.Database.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.SeasonMatch", "SeasonMatch")
                        .WithMany()
                        .HasForeignKey("SeasonMatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("RequestedByUser");

                    b.Navigation("SeasonMatch");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchTeam", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.Match", "Match")
                        .WithMany("MatchTeams")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedKickVote", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.MatchedPlayer", "KickMatchedPlayer")
                        .WithMany("KickMatchedKickVotes")
                        .HasForeignKey("KickMatchedPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.MatchedMatch", "MatchedMatch")
                        .WithMany("MatchedKickVotes")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.MatchedPlayer", "VoterMatchedPlayer")
                        .WithMany("VoterMatchedKickVotes")
                        .HasForeignKey("VoterMatchedPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KickMatchedPlayer");

                    b.Navigation("MatchedMatch");

                    b.Navigation("VoterMatchedPlayer");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedMatch", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.MatchedTeam", "AwayTeam")
                        .WithOne("AwayMatchedMatch")
                        .HasForeignKey("GrifballWebApp.Database.Models.MatchedMatch", "AwayTeamId");

                    b.HasOne("GrifballWebApp.Database.Models.MatchedTeam", "HomeTeam")
                        .WithOne("HomeMatchedMatch")
                        .HasForeignKey("GrifballWebApp.Database.Models.MatchedMatch", "HomeTeamId");

                    b.HasOne("GrifballWebApp.Database.Models.Match", "Match")
                        .WithOne("MatchedMatch")
                        .HasForeignKey("GrifballWebApp.Database.Models.MatchedMatch", "MatchID");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedPlayer", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.MatchedTeam", "MatchedTeam")
                        .WithMany("Players")
                        .HasForeignKey("MatchedTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.User", "User")
                        .WithMany("MatchedPlayers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchedTeam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedWinnerVote", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.MatchedMatch", "MatchedMatch")
                        .WithMany("MatchedWinnerVotes")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.MatchedPlayer", "MatchedPlayer")
                        .WithMany("MatchedWinnerVotes")
                        .HasForeignKey("MatchedPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchedMatch");

                    b.Navigation("MatchedPlayer");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Medal", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.MedalDifficulty", "MedalDifficulty")
                        .WithMany("Medals")
                        .HasForeignKey("MedalDifficultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.MedalType", "MedalType")
                        .WithMany("Medals")
                        .HasForeignKey("MedalTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedalDifficulty");

                    b.Navigation("MedalType");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MedalEarned", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.Medal", "Medal")
                        .WithMany("MedalEarned")
                        .HasForeignKey("MedalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.MatchParticipant", "MatchParticipant")
                        .WithMany("MedalEarned")
                        .HasForeignKey("MatchID", "XboxUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchParticipant");

                    b.Navigation("Medal");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.PasswordResetLink", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.QueuedPlayer", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.User", "User")
                        .WithOne("QueuedPlayer")
                        .HasForeignKey("GrifballWebApp.Database.Models.QueuedPlayer", "UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SeasonAvailability", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.AvailabilityOption", "AvailabilityOption")
                        .WithMany("SeasonAvailability")
                        .HasForeignKey("AvailabilityOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.Season", "Season")
                        .WithMany("SeasonAvailability")
                        .HasForeignKey("SeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilityOption");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SeasonMatch", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.MatchReschedule", "ActiveRescheduleRequest")
                        .WithOne()
                        .HasForeignKey("GrifballWebApp.Database.Models.SeasonMatch", "ActiveRescheduleRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GrifballWebApp.Database.Models.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GrifballWebApp.Database.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GrifballWebApp.Database.Models.Season", "Season")
                        .WithMany("SeasonMatches")
                        .HasForeignKey("SeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveRescheduleRequest");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SeasonSignup", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.Season", "Season")
                        .WithMany("SeasonSignups")
                        .HasForeignKey("SeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.User", "User")
                        .WithMany("SeasonSignups")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SignupAvailability", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.AvailabilityOption", "AvailabilityOption")
                        .WithMany("SignupAvailability")
                        .HasForeignKey("AvailabilityOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.SeasonSignup", "SeasonSignup")
                        .WithMany("SignupAvailability")
                        .HasForeignKey("SeasonSignupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilityOption");

                    b.Navigation("SeasonSignup");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Team", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.TeamPlayer", "Captain")
                        .WithOne("CaptainTeam")
                        .HasForeignKey("GrifballWebApp.Database.Models.Team", "CaptainID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GrifballWebApp.Database.Models.Season", "Season")
                        .WithMany("Teams")
                        .HasForeignKey("SeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Captain");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.TeamAvailability", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.AvailabilityOption", "AvailabilityOption")
                        .WithMany("TeamAvailability")
                        .HasForeignKey("AvailabilityOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.Team", "Team")
                        .WithMany("TeamAvailability")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilityOption");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.TeamPlayer", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.Team", "Team")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.User", "User")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.User", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.DiscordUser", "DiscordUser")
                        .WithOne("User")
                        .HasForeignKey("GrifballWebApp.Database.Models.User", "DiscordUserID");

                    b.HasOne("GrifballWebApp.Database.Models.Region", "Region")
                        .WithMany("Users")
                        .HasForeignKey("RegionID");

                    b.HasOne("GrifballWebApp.Database.Models.XboxUser", "XboxUser")
                        .WithOne("User")
                        .HasForeignKey("GrifballWebApp.Database.Models.User", "XboxUserID");

                    b.Navigation("DiscordUser");

                    b.Navigation("Region");

                    b.Navigation("XboxUser");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.UserClaim", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.UserExperience", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.GameVersion", "GameVersion")
                        .WithMany("UserExperiences")
                        .HasForeignKey("GameVersionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.User", "User")
                        .WithMany("PersonExperiences")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.UserLogin", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.UserRole", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrifballWebApp.Database.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GrifballWebApp.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.AvailabilityOption", b =>
                {
                    b.Navigation("SeasonAvailability");

                    b.Navigation("SignupAvailability");

                    b.Navigation("TeamAvailability");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.DiscordUser", b =>
                {
                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.GameVersion", b =>
                {
                    b.Navigation("UserExperiences");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Match", b =>
                {
                    b.Navigation("MatchLink");

                    b.Navigation("MatchTeams");

                    b.Navigation("MatchedMatch");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchBracketInfo", b =>
                {
                    b.Navigation("InverseAwayTeamNextMatchBracketInfo");

                    b.Navigation("InverseHomeTeamPreviousMatchBracketInfo");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchParticipant", b =>
                {
                    b.Navigation("MedalEarned");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchTeam", b =>
                {
                    b.Navigation("MatchParticipants");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedMatch", b =>
                {
                    b.Navigation("MatchedKickVotes");

                    b.Navigation("MatchedWinnerVotes");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedPlayer", b =>
                {
                    b.Navigation("KickMatchedKickVotes");

                    b.Navigation("MatchedWinnerVotes");

                    b.Navigation("VoterMatchedKickVotes");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MatchedTeam", b =>
                {
                    b.Navigation("AwayMatchedMatch");

                    b.Navigation("HomeMatchedMatch");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Medal", b =>
                {
                    b.Navigation("MedalEarned");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MedalDifficulty", b =>
                {
                    b.Navigation("Medals");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.MedalType", b =>
                {
                    b.Navigation("Medals");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Region", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Season", b =>
                {
                    b.Navigation("SeasonAvailability");

                    b.Navigation("SeasonMatches");

                    b.Navigation("SeasonSignups");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SeasonMatch", b =>
                {
                    b.Navigation("BracketMatch");

                    b.Navigation("MatchLinks");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.SeasonSignup", b =>
                {
                    b.Navigation("SignupAvailability");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("TeamAvailability");

                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.TeamPlayer", b =>
                {
                    b.Navigation("CaptainTeam");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.User", b =>
                {
                    b.Navigation("MatchedPlayers");

                    b.Navigation("PersonExperiences");

                    b.Navigation("QueuedPlayer");

                    b.Navigation("SeasonSignups");

                    b.Navigation("TeamPlayers");

                    b.Navigation("UserClaims");

                    b.Navigation("UserLogins");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GrifballWebApp.Database.Models.XboxUser", b =>
                {
                    b.Navigation("MatchParticipants");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
