using GrifballWebApp.Database;
using Microsoft.EntityFrameworkCore;

namespace GrifballWebApp.Test;
public static class ContextExtensions
{
#pragma warning disable EF1002 // Risk of vulnerability to SQL injection.
    // Explicit values in identity columns: SQL Server refuses them unless IDENTITY_INSERT is on.
    // Postgres takes them (GENERATED BY DEFAULT), but its sequence doesn't move past them, so it is
    // moved afterwards. table: [Schema].[Table] or Schema.Table.
    public static async Task DisableContraints(this GrifballContext _context, string table)
    {
        if (TestDatabase.Provider == DatabaseProvider.SqlServer)
            await _context.Database.ExecuteSqlRawAsync($"SET IDENTITY_INSERT {table} ON");
    }

    public static async Task EnableContraints(this GrifballContext _context, string table)
    {
        if (TestDatabase.Provider == DatabaseProvider.SqlServer)
            await _context.Database.ExecuteSqlRawAsync($"SET IDENTITY_INSERT {table} OFF");
        else
            await _context.ResyncIdentity(table);
    }

    /// <summary>Postgres: the table's identity sequence continues after its highest key.</summary>
    private static async Task ResyncIdentity(this GrifballContext _context, string table)
    {
        var parts = table.Split('.').Select(p => p.Trim('[', ']', '"')).ToArray();
        var (schema, name) = parts.Length == 2 ? (parts[0], parts[1]) : ("public", parts[0]);
        var entityType = _context.Model.GetEntityTypes()
            .First(e => e.GetTableName() == name && (e.GetSchema() ?? "public") == schema);
        var identity = entityType.FindPrimaryKey()!.Properties
            .Single(p => p.ValueGenerated == Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.OnAdd);
        var column = identity.GetColumnName();
        await _context.Database.ExecuteSqlRawAsync(
            $"SELECT setval(pg_get_serial_sequence('\"{schema}\".\"{name}\"', '{column}'), COALESCE(MAX(\"{column}\"), 0) + 1, false) FROM \"{schema}\".\"{name}\"");
    }

    public static async Task SaveChangesWithoutConstraints(this GrifballContext _context)
    {
        // Get all entities being added
        var entries = _context.ChangeTracker.Entries()
            .Where(e => e.State == EntityState.Added)
            .Select(e => e.Metadata)
            .Distinct()
            .ToList();

        // Find tables with identity columns
        var tablesWithIdentity = new List<(string Schema, string Table)>();
        foreach (var entityType in entries)
        {
            var key = entityType.FindPrimaryKey();
            if (key == null) continue;

            // Find if any PK property is identity
            var identityProp = key.Properties.FirstOrDefault(p =>
                p.ValueGenerated == Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.OnAdd &&
                p.GetAnnotations().Any(a => a.Name is "SqlServer:ValueGenerationStrategy" or "Npgsql:ValueGenerationStrategy" && a.Value?.ToString()?.Contains("Identity") == true)
            );
            if (identityProp == null) continue;

            var any = _context.ChangeTracker.Entries()
                .Where(e => e.State == EntityState.Added)
                .Where(e => e.Entity.GetType() == entityType.ClrType)
                .Where(e =>
                {
                    if (identityProp.PropertyInfo is null)
                        return false;
                    var current = e.Property(identityProp.Name).CurrentValue;
                    var bar = current != default;
                    if (identityProp.ClrType == typeof(int))
                    {
                        return (int)current! > 0;
                    }
                    else if (identityProp.ClrType == typeof(long))
                    {
                        return (long)current! > 0;
                    }
                    else
                    {
                        return current != default;
                    }
                })
                .ToList();

            if (any.Any() is false)
            {
                continue;
            }

            var tableName = entityType.GetTableName();
            var schema = entityType.GetSchema() ?? "dbo";
            if (tablesWithIdentity.Any())
                throw new Exception("Unable to save identity column for more than one column at once");
            tablesWithIdentity.Add((schema, tableName));
        }

        // Use a transaction
        using var tx = await _context.Database.BeginTransactionAsync();

        try
        {
            // Disable constraints for each table
            foreach (var (schema, table) in tablesWithIdentity)
                await _context.DisableContraints($"[{schema}].[{table}]");

            await _context.SaveChangesAsync();

            // Enable constraints for each table
            foreach (var (schema, table) in tablesWithIdentity)
                await _context.EnableContraints($"[{schema}].[{table}]");

            await tx.CommitAsync();
        }
        catch
        {
            await tx.RollbackAsync();
            throw;
        }
    }
#pragma warning restore EF1002 // Risk of vulnerability to SQL injection.
}
