/**
 * This file is AUTO-GENERATED by generate-coverage-imports.js
 * DO NOT EDIT MANUALLY
 * 
 * This file ensures all source files are included in code coverage,
 * even if they don't have their own test files.
 * 
 * To regenerate: npm run generate-coverage-imports
 */

import './accessTokenResponse';
import './account.service';
import './api/apiClient.service';
import './api/dtos/AddPlayerToTeamRequestDto';
import './api/dtos/MovePlayerToTeamRequestDto';
import './api/dtos/RemovePlayerFromTeamRequestDto';
import './api/dtos/availabilityOption';
import './api/dtos/captainDto';
import './api/dtos/captainPlacementDto';
import './api/dtos/killsDto';
import './api/dtos/loginDto';
import './api/dtos/playerDto';
import './api/dtos/registerDto';
import './api/dtos/seasonDto';
import './api/dtos/signupRequestDto';
import './api/dtos/signupResponseDto';
import './api/dtos/teamResponseDto';
import './api/signalR.service';
import './app.component';
import './app.routes';
import './auth.interceptor';
import './availability.service';
import './commissioner-dashboard/commissioner-dashboard.component';
import './commissioner-dashboard/process-reschedule-dialog/process-reschedule-dialog.component';
import './excel/excel.component';
import './excel/excelForm/excelForm.component';
import './home/home.component';
import './infiniteClient/infiniteClient.component';
import './isEventOrganizer.guard';
import './isSysAdmin.guard';
import './lateLeague/lateLeague.component';
import './login/login.component';
import './notFound/notFound.component';
import './profile/profile.component';
import './register/register.component';
import './register/registerFormModel';
import './reschedule-request/reschedule-request.component';
import './season/playerGrades/gradesDto';
import './season/playerGrades/playerGrades.component';
import './season/playoffBracket/createBracketDialog/createBracketDialog.component';
import './season/playoffBracket/playoffBracket.component';
import './season/playoffBracket/seedOrderingDialog/seedOrderingDialog.component';
import './season/scheduleList/createRegularMatchesDialog/createRegularMatchesDialog.component';
import './season/scheduleList/scheduleList.component';
import './season/scheduleList/scheduledMatchDto';
import './season/scheduleList/timeDto';
import './season/scheduleList/unscheduledMatchDto';
import './season/scheduleList/updateMatchTimeDto';
import './season/scheduleList/weekDto';
import './season/season.component';
import './season/seasonMatch/possibleMatchDto';
import './season/seasonMatch/seasonMatch.component';
import './season/seasonMatch/seasonMatchPageDto';
import './season/team/team.component';
import './season/teamStandings/teamStandingDto';
import './season/teamStandings/teamStandings.component';
import './seasonEdit/seasonAvailability/seasonAvailability.component';
import './seasonEdit/seasonEdit.component';
import './seasonManager/seasonManager.component';
import './shared/getPaginationResource';
import './shared/paginationResult';
import './shared/searchBox/searchBox.component';
import './shared/table/table.component';
import './sidebarDto';
import './signupForm/availabilityTable/availabilityTable.component';
import './signupForm/signupForm.component';
import './signups/signups.component';
import './teamBuilder/personStatus';
import './teamBuilder/teamBuilder.component';
import './teamBuilder/teamModel';
import './theme.service';
import './theme/palette/palette.component';
import './theme/palette/tile/tile.component';
import './theme/paletteTypes';
import './theme/theme.component';
import './theming.service';
import './toolbar/toolbar.component';
import './top-stats/top-stats.component';
import './userManagement/createUser/createUser.component';
import './userManagement/createUser/createUserDto';
import './userManagement/editUser/editUser.component';
import './userManagement/mergeUser/mergeUser.component';
import './userManagement/mergeUser/userDetail/userDetail.component';
import './userManagement/userManagement.component';
import './userManagement/userResponseDto';
import './validation/directives/matchFieldsValidator.directive';
import './validation/directives/regexMatchValidValidatorDirective.directive';
import './validation/errorMessage.component';
import './validation/validationService';
import './validation/validators/matchFieldsValidator';
import './validation/validators/regexMatchValidator';

describe('Coverage Import', () => {
  it('should import all source files for coverage', () => {
    // This test doesn't need to do anything - it just needs to exist
    // so that all the imports above are processed by the test runner
    expect(true).toBe(true);
  });
});
