name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build the backend
      run: docker build . -f GrifballWebApp.Server/Dockerfile -t ghcr.io/${{ github.repository }}/grifballwebappserver:latest
      
    - name: Build the frontend
      run: docker build grifballwebapp.client -f grifballwebapp.client/Dockerfile -t ghcr.io/${{ github.repository }}/grifballwebappclient:latest

    - name: Push the backend
      run: docker push ghcr.io/${{ github.repository }}/grifballwebappserver:latest

    - name: Push the frontend
      run: docker push ghcr.io/${{ github.repository }}/grifballwebappclient:latest
      
